accounts/urls.py
from django.urls import path
from .views import UserRegistrationView, LogoutView, UserLoginView, Sure_kuleft,ProfileDetailView, CardyView, CardyCreateMixin
from mpesa.views import stk
from sleek_profile import views


app_name = 'accounts'

urlpatterns = [
    path("login/", UserLoginView.as_view(), name="user_login"),
    path("out", LogoutView.as_view(), name="optout"),
    path("logout/", Sure_kuleft, name="user_logout"),
    path("register/", UserRegistrationView.as_view(), name="user_registration"),
    path("cards/", CardyView.as_view(), name="cards"),
    path('mpesa/stk', stk, name='stk_signup'),
    path('stk', stk, name='deposit'),
    path('cardy', CardyCreateMixin.as_view(), name='cardy'),
    path("settings", views.ex_setting, name="ex_setting"),
    path('profile/<str:pk>/<user>', ProfileDetailView.as_view(), name='ProfileDetail'),
   
]

openSoko/urls.py
from django.urls import path
from .views import (
    ItemDetailView,
    CheckoutView,
    HomeView,
    DeliveryView,
    OrderSummaryView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    add_single_item_to_cart,
    PaymentView,
    AddCouponView,
    RequestRefundView,
    ItemPostView,
    Items_upload,
    map,
)

app_name = 'openSoko'

urlpatterns = [
    path('openSoko', HomeView.as_view(), name='openSoko'),
    path('delivery/<user>/<pk>/', DeliveryView.as_view(), name='delivery'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add_product', Items_upload, name='add_product'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove_single_item_from_cart/<slug>/', remove_single_item_from_cart, name='remove_single_item_from_cart'),
    path('add_single_item_to_cart/<slug>/', add_single_item_to_cart, name='add_single_item_to_cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('request-refund', RequestRefundView.as_view(), name='request-refund'),
    path('ItemPost/<user>/', ItemPostView.as_view(), name='ItemPost'),
    path('map', map, name='map')
]

plug/urls.py
from django.urls import path
from . import views
from .views import MboaNFTs


urlpatterns = [
	path('', views.PostsView.index, name='index'),
	path('settings', views.settings, name='settings'),
	path('upload', views.upload, name='upload'),
	path('post', views.Plug_Products.posts, name='posts'),
	path('plug/follow/', views.follow, name='follow'),
	path('Ma-Plug/', views.Ma_Plug, name='Ma_Plug'),
	path('wasee/', views.Plug_Products.wasee, name='wasee'),
	path('Mali', views.Plug_Products.as_view(), name='Mali'),
	path('posts', views.PostsView.as_view(), name='pos'),
	path('search', views.search, name='search'),
	path('profile/<str:pk>/<user>', views.Plug_Products.as_view(), name='plug_profile'),
	path('like-post', views.like_post, name='like_post'),
	path('MboaNFTs', MboaNFTs, name='MboaNFTs'),

]

sleek_main_hub/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	# For login to the Administrator Portal Only For SuperUsers
	path('admin/', admin.site.urls),
	
	
	# Can be accessed without Registration or login to the system. Basic lightweight function that require no Identity
	path('', include('sleek_profile.urls'), name="dashboard"),
	path('plug/', include('plug.urls'), name="plug"),
	path('', include('openSoko.urls', namespace="core"), name="core"),
	path('users/', include('plug.urls'), name="plug"),

	path("__reload__/", include("django_browser_reload.urls")),
	
	
	path('accounts/', include('accounts.urls'), name='accounts'),
	path('Notification/', include('conversation.urls'), name='banja'),
	path('mpesa/', include('mpesa.urls'), name='mpesa'),
	path('transactions/', include('transactions.urls'), name='transactions'),
	path('peer_to_peer/', include('peer_to_peer.urls'), name="peer_to_peer"),
	path('positions/', include('positions.urls'), name="positions"),
	
	
]
urlpatterns = urlpatterns+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = urlpatterns+static(settings.MBOA_ID_URL, document_root=settings.MBOA_ID_ROOT)

transactions/urls.py
from django.urls import path
from mpesa import views
from .views import DepositMoneyView, WithdrawMoneyView, LoanView, TransactionRepostView, eshopCart, MboaCoins, Invest


app_name = 'transactions'


urlpatterns = [
    path("stk", views.stk, name="stk"),
    path("deposit/", DepositMoneyView.as_view(), name="deposit_money"),
    path("report/", TransactionRepostView.as_view(), name="transaction_report"),
    path("withdraw/", WithdrawMoneyView.as_view(), name="withdraw_money"),
    path("mboapay/", eshopCart.as_view(), name="mboapay"),
    path("Invest", Invest, name="Invest"),
    path("mboaCoins/", MboaCoins.as_view(), name="eshopcart"),
    path("Loan", LoanView.as_view(), name="Loan"),
]

templates/core/MboaCoins.html
{% load static %}

      <div style="width:100%;margin-bottom:20px; margin-right: 10px; height:50vh;" class="bty">

<header style="height:2vh;  box-shadow: 10px 0px 34px 50px #fff;background-color:#fff;"> </header>
{% if request.user.is_authenticated %}
<form action="{% url 'stk' %}" method="POST" >
                                                             {% csrf_token %}
                                                             <input type="text" id="phone_number"  hidden  readonly value="0{{user.address.postal_code}}" name="phone_number" placeholder="phone number" class="btn form-control" required autofocus    style="font-family:Comic Sans Mn;font-size:24px;text-align:center; margin-top:5px;border-radius:10px;height:7vh; width:100%; "><br>
                                                             <input type="number" id="amount" hidden  readonly value="{{ user.account.balance }}" required name="amount" class=" btn form-control" placeholder="Amount " style="font-family:Comic Sans Mn;font-size:24px;text-align:center; height:7vh;margin-top:20px; margin-bottom:70px;border-radius:10px; width:100%;">
             <button style="border-radius:20px; padding:2px;margin-left:10%;margin-top:80vh;width:60%; " type="submit" class="btn btn-md my-0 p">
              Buy |  <img style="width:50px; font-size:40%;  height:40px;"   src="{% static '/img/mpesa.png'%}">
            </button>
                   </form>


 {% else %}
            <div>
                <a href="/Deposit" class="btn mr-2 inline-block font-medium text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-gray-800 hover:bg-white mt-4 lg:mt-0">Buy  | <img style="width:50px; font-size:40%;  height:40px;"   src="{% static '/img/mpesa.png'%}">
                </a></div>
{% endif %}
<form>
    <div style="display:flex; flex-direction:row; margin-top:20px;">
<div class="bty" style="background-color:#008800; width:85px;height:40px;margin-right:-20;">
    <p>Ksh.</p>
    </div>
        <input   style="color: #001100;text-align:center; width:90%;height:40px;margin-right:40% background-color:transparent;" class="bty shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight border rounded-md border-gray-500 focus:outline-none focus:shadow-outline" name="amount" id="amount" type="number" required placeholder=" Enter Amount ">


    </div></form><br>
<p style="font-size:80%;">Mboa Coins to Receive...</p>

             <div class="btn" style="border-radius:7px;width:100%;height:50px;text-align:center;">

             </div>
</div>

templates/core/MpesaButton.html
{% load static %}

{% if request.user.is_authenticated %}
<form  action="stk" method="POST" >
                                                             {% csrf_token %}
                                                             <input type="text" id="phone_number"  hidden  readonly value="0{{user.address.postal_code}}" name="phone_number" placeholder="phone number"
                                                              class="btn form-control" required autofocus    style="font-family:Comic Sans Mn;font-size:24px;text-align:center; margin-top:5px;border-radius:10px;height:7vh; width:100%; "><br>
                                                             <input type="number" id="amount" hidden  readonly value="{{item.price}}" required name="amount" class=" btn form-control" placeholder="Amount " style="font-family:Comic Sans Mn;font-size:24px;text-align:center; height:7vh;margin-top:20px; margin-bottom:70px;border-radius:10px; width:100%;">
             <button style="border-radius:20px; padding:2px;margin-top:80vh;width:100%; " type="submit" class="btn btn-md my-0 font-family:Comic Sans Mn; font-weight-bold black-text p">
              Buy Now |  <img style="width:50px; font-size:40%;  height:40px;"   src="{% static '/img/mpesa.png'%}">
            </button>
                   </form>

 {% else %}
            <div style="margin-top:50px;" class="text-md lg:flex-grow"></div>
            <div>
                <a href="/Deposit" class="bty mr-2 inline-block font-medium text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-gray-800 hover:bg-white mt-4 lg:mt-0">Buy  | <img style="width:50px; font-size:40%;  height:40px;"   src="{% static '/img/mpesa.png'%}">
                </a></div>
{% endif %}

templates/core/No_base.html
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8" />
          <link style="width:50px;height:50px;border-radius:100%;" rel="shortcut icon" href="{% static 'img/Mboa Academy.jpg '%}"  id="icon" >
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="New Wave of Kenyan trade and investing in digital assets" />
        <meta name="author" content="Mboa Technologies" />
        <title>
            {% block head_title %}Sleek.ke -Buy Digital Assets{% endblock %}
        </title>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Tangerine">
      <link rel="stylesheet" href="{% static 'style.css' %}">
      <link rel="stylesheet" href="{% static 'css/style.css' %}">
       <link rel="stylesheet" href="{% static 'css/font-awesome.css' %}">

        {% block head_extra %}{% endblock %}
    </head>
     <!-- PG Start -->
   <!-- PG End -->
     <div class="page-loader">
      <div></div>
      <div></div>
      <div></div>
   </div>
   <!-- BG Start -->
   <div class="bg-circles">
      <div class="circle-1"></div>
      <div class="circle-2"></div>
      <div class="circle-3"></div>
      <div class="circle-5"></div>
      <div class="circle-8"></div>
      <div style="background-color:transparent;" class="circle-4"><img style="width:100% ;  height:100%;border-radius:50%;"   src="{% static 'img/KenyanBrand.jpg'%}" alt="KenyanBrand"></div>

   </div>
   <!-- BG End -->
   <!-- Overlay Start -->
   <div class="overlay"></div>
   <!-- Overlay End -->
    <body  class="bg-gray-100" style="font-weight:bold;">
        {% block body %}

        <div class="main hidden" >
         <!-- Header Start -->
             <div   class="container">
         <header class="header">

               <div class="row flex-end">
                  <button type="button" class="nav-toggler">
                  <span></span> </button>
                  <div class="nav">
                     <div  style="background-color:rgba(0,0,0,0.2);
        opacity:90%; border-radius:40px;backdrop-filter:blur(10px);border:2px solid rgba(255,255,255,0.2);z-index:10;display:flex;box-shadow:40px 40px 40px 80px rgba(0,0,0,0.3);" class="nav-inner">
                          <div  style="" class="home-img">

                         <div style=" font-width:500px bold;color:#008800;margin:10px 10px;" class="about-tabs">
{% include 'core/navbar.html' %}
                         </div>
                              </div>
                     </div>

                  </div>
                                    </div>
         </header>  </div>
         </div>

         <!-- Header End -->
         <!--Home Section Start -->

            <div class="lg:container lg:mx-auto">

                {% block content %}
                 {% include 'core/messages.html' %}
                <!-- Add content here -->
                {% endblock %}
            </div>
        {% endblock %}

    </body>


<div style="background-color:rgba(0,0,0,0.2);
        opacity:100%; border-radius:1px;backdrop-filter:blur(10px);border:2px solid rgba(255,255,255,0.2);z-index:10;display:flex;box-shadow:40px 40px 40px 80px rgba(0,0,0,0.3);" class="portfolio-popup">
         <div class="pp-inner">
            <div class="pp-content">
               <div class="pp-header">
                  <button type="button" class="btn pp-close">
                      <i class="fas fa-times"> </i> </button>

                  </div>
                        {% include 'mpesa/LipaNaMpesa.html' %}
               </div>
               <div class="pp-body">
               </div>

            </div>
         </div>

      <!-- Portfolio Item Details Popup Start -->
<script src="{% static 'js/script.js' %}"></script>
</html>

templates/core/Twin.html
{% load cart_template_tags %}

<nav  class="navbar align-items-center fixed-top navbar-expand-lg navbar-light scrolling-navbar" style="background-color:rgba(0,0,0,0.2);
         opacity:70%; margin-top:-1ovh;backdrop-filter:blur(10px);border:2px solid rgba(255,255,255,0.2);z-index:10;display:flex; flex-direction:row;box-shadow:40px 40px 40px 80px rgba(0,0,0,0.3);">
    <div class="container">

      <!-- Brand -->
        {% if request.user.is_authenticated %}
<!--      <a href="/">-->
<!--      <img  class="img-fluid" style="margin-left:2px;width:50px; height:50px ; border-radius:100%; opacity:100%; margin-top:1vh;" src=" {{user.address.profileimg.url}}"  alt="Profile Picture for {{ user.first_name }}">-->
<!--      </a>-->

        <button style="padding:4px;display:flex;flex-direction:row;width:100%;border-radius:40px;" class=" btn " type="button"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <a href="/" >
      <img  class="img-fluid" style="width:35px;height:30px;margin-top:0.5vh;margin-left:0.5vw; border-radius:100%; opacity:100%; " src=" {{user.address.profileimg.url}}"  alt="Profile Picture for {{ user.first_name }}">
           </a>
            <a href="/openSoko">
       <h6  style="margin-top:0.5vh;color:#001100;font-weight:bold;padding:1;border:none;font-family:Comic Sans Mn; font-size:130%; margin-left:40%;text-align:center;" class="bty navbar-brand waves-effect">    <strong class="black-text">openSoko</strong>  </h6>
      </a>
       <a style="margin-top:0.5vh;margin-left:40%; " href="{% url 'core:order-summary' %}"><span  class="fas fa-shopping-cart"> </span></a>
    <span style="margin-left:-2px;background-color:#6BBE4E;" class="badge  badge-pill">{{ order.items.count }}</span>
      </button>
       {% else %}
      <a href="/accounts/login">
        <h1  style="font-weight:bold;font-family:Comic Sans Mn; font-size:150%;  text-align:center;" class="bty navbar-brand waves-effect">    <strong >openSoko</strong>  </h1>
      </a>
        {% endif %}



      <!-- Collapse -->


      <!-- Links   class="navbar-toggler-icon"   <i class="fas fa-shopping-cart"></i>-->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          {% comment %} <li class="nav-item active">
            <a class="nav-link waves-effect" href="/">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="/checkout">
            Checkout</a>
          </li> {% endcomment %}
        </ul>

        <!-- Right -->
      </div>

    </div>
  </nav>

templates/core/base.html
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8" />
          <link style="width:50px;height:50px;border-radius:100%;" rel="shortcut icon" href="{% static 'img/Mboa Academy.jpg '%}"  id="icon" >
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="New Wave of Kenyan trade and investing in digital assets" />
        <meta name="author" content="Mboa Technologies" />
        <title>
            {% block head_title %}Sleek.ke -Buy Digital Assets{% endblock %}
        </title>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Tangerine">
      <link rel="stylesheet" href="{% static 'style.css' %}">
      <link rel="stylesheet" href="{% static 'css/style.css' %}">
       <link rel="stylesheet" href="{% static 'css/font-awesome.css' %}">

        {% block head_extra %}{% endblock %}
    </head>
     <!-- PG Start -->
   <!-- PG End -->
     <div class="page-loader">
      <div></div>
      <div></div>
      <div></div>
   </div>
   <!-- BG Start -->
   <div class="bg-circles">
      <div class="circle-1"></div>
      <div class="circle-2"></div>
      <div class="circle-3"></div>
      <div class="circle-5"></div>
       <div style=" background:url({% static 'img/KenyanBrand.jpg' %});" class="circle-4"></div>
   </div>
   <!-- BG End -->
   <!-- Overlay Start -->
   <div class="overlay"></div>
   <!-- Overlay End -->
    <body  class="bg-gray-100">
        {% block body %}

        <div class="main hidden" >
         <!-- Header Start -->

         <header class="header">
<div   class="container">
               <div class="row flex-end">
            <button style="margin-top:6vh;margin-right:8%;" type="button" class="nav-toggler">
                  <span></span>
                  </button>
                  <div class="nav">
                     <div  style="background-color:rgba(0,0,0,0.2);
         border-radius:40px;backdrop-filter:blur(10px);border:2px solid rgba(255,255,255,0.2);z-index:10;display:flex;box-shadow:40px 40px 40px 80px rgba(0,0,0,0.3);" class="nav-inner">
                          <div  style="" class="home-img">
                         <div style=" font-width:500px bold;color:#008800;margin:10px 10px;" class="about-tabs">
{% include 'core/navbar.html' %}
                         </div>
                              </div>
                     </div>

                  </div>
                                    </div>
</div> </header>


         <!-- Header End -->
         <!--Home Section Start -->
            <div class="lg:container lg:mx-auto">

                {% block content %}
                 {% include 'core/messages.html' %}
                <!-- Add content here -->
                {% endblock %}
            </div>
            {% include 'core/footer.html' %}

        {% endblock %}
        {% block footer_extra %}{% endblock %}
        </div> </body>


<div  class="portfolio-popup" style="background-color:rgba(0,0,0,0.2);
        opacity:100%; backdrop-filter:blur(10px);border:2px solid rgba(255,255,255,0.2);z-index:10px;box-shadow:40px 40px 40px 80px rgba(0,0,0,0.3);">
         <div class="pp-inner">
            <div class="pp-content">
               <div class="pp-header">
                  <button type="button" class="btn pp-close">
                      <i class="fas fa-times"> </i> </button>

                  </div>
                        {% include 'mpesa/LipaNaMpesa.html' %}
               </div>
               <div class="pp-body">
               </div>

            </div>
         </div>

      <!-- Portfolio Item Details Popup Start -->
<script src="{% static 'js/script.js' %}"></script>
</html>

templates/core/footer.html
{% load static%}
<footer  style="margin-top:30%; " class="footer bg-gray-200 relative pt-1 border-b-2 mt-10">



    <div class="container mx-auto px-6">
<!--        <div class="page-loader">-->
<!--      <div></div>-->
<!--      <div></div>-->
<!--      <div></div>-->
<!--   <div class="bg-circles">-->

<!--   </div>-->
<!--        </div>-->
        <center>
        <div class="mt-5 flex flex-col items-center">
                <div class="sm:w-2/3 text-center py-6">
                <a  class="bty black-text p" style="font-weight:bold;color:#000; border:none;" href="/page"><img style="width:80px; height:80px ;border-radius:100%;margin-bottom:5px; "  src="{%static 'img/Mboa Academy.jpg'%}" alt="Mboa Technology">
                <p class="my-2 font-bold mb-2">
                      Mboa Technologies
                </p>
                </a>
           <button  style="font-weight:bold;background-color:#DCECC8;border-radius:20px; padding:2px;margin-top:5vh;width:100%; "  class=" view-project-btn btn btn-md mb-8 my-2 font-family:Comic Sans Mn; font-weight-bold black-text p">
            Donate |  <img style="width:50px; font-size:40%;  height:40px;"   src="{% static '/img/mpesa.png'%}"></button>
            </div>
        </div>
        </center>
    </div>
</footer>

templates/core/messages.html
{% for message in messages %}

<!--
<div  class="bty bg-teal-100 border-t-4 border-teal-500 rounded-b text-teal-900 px-4 py-3 shadow-md mt-2"
style=" opacity:100%;z-index:10;backdrop-filter:blur(10px);margin-top:10px; margin-bottom:5%; width:75%;height:18vh;color:#001100; background-color:#6BBE4E;"  role="alert"> -->
<!--            <div class="flex"> -->
<!--             <p style="color:yellow;" class="font-bold">Success!</p> -->
<!--             <p style="color:#001100;margin-top:10px;" class="text-sm block sm:inline">{{ message }}</p> -->
<!--         </div> -->
<!-- </div> -->
<!--
background-color:rgba(0,0,0,0.2);
        border-radius:40px;border:2px solid rgba(255,255,255,0.2);display:flex;box-shadow:40px 40px 40px 80px rgba(0,0,0,0.3);
        -->

       <div  class="bty bg-teal-100 border-t-4 border-teal-500 rounded-b text-teal-900 px-4 py-3 shadow-md mt-2">

       </div> {% endfor %}

templates/core/navbar.html
{% load static %}
<nav style="margin-left:40px margin-bottom:4px;" class="flex items-center justify-between flex-wrap bg-gray-800 p-6">
    <div class="w-full block flex-grow lg:flex lg:items-center lg:w-auto">
        <img style="width:80% ; margin-top:-10%;opacity:20%;  height:50%;border-radius:50%;"   src="{% static 'img/shootCenterBanner.png'%}" alt="KenyanBrand">
        {% if request.user.is_authenticated %}

            <div style="font-family:Comic Sans Mn; margin-top:-80%; margin-bottom:2px;" class=" text-md lg:flex-grow">
                <div style="color:#000;font-weight:bold;font-size:24px;" class="about-tabs">
               <div style="border:none; background-color:#ffffff00; flex-direction: row;display: flex;border-radius:7px;margin-bottom:5px;margin-right:1vw;margin-left:1vw; margin-top:5vh;"  >
            <div style="width:50%;  border-radius:10px; height:10vh;" class="btn"><a style="margin-left:-20px;" href="/setting" type="button" class="tab-item active">Settings</a> </div>
                        <div style="width:50%; border-radius:10px; height:10vh;margin-left:5px;" class="btn"> <a style="margin-left:-20px;" href="/accounts/cardy" type="button" class="tab-item  "> Sleek-ID</a> </div>
               <div style="width:50%;  border-radius:10px; height:10vh;margin-left:5px;" class="btn"><a  style="margin-left:-20px;" href="/wallet" type="button" class="tab-item">Wallet</a> </div>
 </div>
                        <a  style="font-weight:bold;"  href="/positions/" type="button" class="tab-item">Buy Cryptocurrency</a>
                        <a  href="/plug/post" type="button" class="tab-item">Posts</a>
                        <a  href="/Swap" type="button" class="tab-item ">Swap </a>
                       <a  href="/P2P/Bots" type="button" class="tab-item ">Bots</a>
                        <a  href="/MboaEx" type="button" class="tab-item ">About</a>
                        <a  href="/P2P" type="button" class="tab-item ">P2P</a>
                      <a  href="/academy"  type="button" class="tab-item  "> Mboa Academy</a>

                </div>
                <a  style=" background-color:#000;color:#f6f4f1;" href="{% url 'transactions:transaction_report' %}" class=" bty block mt-4 lg:inline-block lg:mt-0 text-white hover:text-white mr-4">
                    History
                </a>
                <a style="background-color:#008800;" href="{% url 'transactions:deposit_money' %}" class=" bty block mt-4 lg:inline-block lg:mt-0 text-white hover:text-white mr-4">
                    Deposit
                </a>
                <br>
                <a  style="color:#F6F8F9; background-color:#6BBE4E;" href="{% url 'transactions:withdraw_money' %}" class="bty block mt-4 lg:inline-block lg:mt-0 text-white hover:text-white">
                    Withdraw
                </a>
                <a href="{% url 'transactions:eshopcart' %}" class="bty block mt-4 lg:inline-block lg:mt-0 text-white hover:text-white">
                    Mboapay
                </a>
<br>
                <a  style="background-color:red;" href="/accounts/logout/" class=" bty inline-block font-medium text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-gray-800 hover:bg-white mt-4 lg:mt-0">Logout</a>

            </div>

        {% else %}
            <div style="margin-top:-10px;" class="text-md lg:flex-grow"></div>
            <div>
                <a href="{% url 'accounts:user_login' %}" class="btn mr-2 inline-block font-medium text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-gray-800 hover:bg-white mt-4 lg:mt-0">Login</a>
            </div>
            <div>
                <a href="{% url 'accounts:user_registration' %}" class="bty inline-block font-medium text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-gray-800 hover:bg-white mt-4 lg:mt-0">Register</a>
            </div>

        {% endif %}
    </div>
  <button   style= " margin-top:5px; color:#008800; background-color:#fff;"  class="btn  view-project-btn  block mt-4 lg:inline-block lg:mt-0 text-white hover:text-white"> <a  style= " color:#008800;" href="/openSoko"> Visit openSoko</a></button>
    <button  style= " margin-top:10px; color:#f6f4f0; background-color:#000;" type="button" class="btn  view-project-btn  block mt-4 lg:inline-block lg:mt-0 text-white hover:text-white"> <a style="color:#f8f0f9;" href="{% url 'MboaEX' %}"> Buy NFTs</a></button>
        <a href="{% url 'transactions:Invest' %}" type="button" style="margin-top:20px;" class="btn   block mt-4 lg:inline-block lg:mt-0 text-white hover:text-white">Invest in Mboa Technologies</a> <br>
</nav>

templates/core/slug.html
{% extends 'core/base.html' %}
{% block head_title %}{{ title }}{% endblock %}

{% block content %}
{%load static%}

<section class="home-section align-items-center" id="home">
            <div class="container">
               <div class="row align-items-center">
                  <div class="home-text">
                     <img  class="logo" src="{% static 'img/Mboa Academy.jpg '%}" alt="profile-img">
                     <h1  >  Sleek-ID</h1>

  <h2>Content Of  {{ user.first_name }}</h2>

                    <pre style="" class="bty">{{ file_content }}</pre>





                  </div>
               </div>

                <center>
                        <div  class="btn">
                         <a style=" color:green;" href="/accounts/register" > Other Members</a>

                   </div>


 </center>
            </div>
    </section>
  {% endblock %}

templates/core/template.html
{% extends 'core/base.html' %}
{% block head_title %}{{ title }}{% endblock %}

{% block content %}
{%load static%}

<section class="home-section align-items-center" id="home">
            <div class="container">
               <div class="row align-items-center">
                  <div class="home-text">
                     <img  class="logo" src="{% static 'img/Mboa Academy.jpg '%}" alt="profile-img">
                     <h1  >  Mboa-ID</h1>


                  </div>
               </div>
            </div>
    </section>
    {% endblock %}
<!--End Of Copy-->



<section class="home-section align-items-center" id ="support">
    <div class="container">
               <div class="row align-items-center">
                  <div class="home-text">
               <div style="width:20vw; height:25%;margin-top:20px;" class="home-img">

<center>
                   <img style="padding:20%; width:100%; height:50%;" class="logoKenya"   src="{% static 'img/KenyanBrand.jpg'%}" alt="profile-img">

</center>
               </div>
                 <p style="margin-top:40px;">Invest You Money In Mboa Technologies by buying <br>Mboa Coins</p>
                 <a  style=" width:100%; padding:20%; position:center;" class="bty" href="/Deposit" ><h1>Support</h1></a>
                  </div>
               </div>
    </div>
</section>