plug/urls.py
from django.urls import path
from . import views
from .views import MboaNFTs


urlpatterns = [
	path('', views.PostsView.index, name='index'),
	path('settings', views.settings, name='settings'),
	path('upload', views.upload, name='upload'),
	path('post', views.Plug_Products.posts, name='posts'),
	path('plug/follow/', views.follow, name='follow'),
	path('Ma-Plug/', views.Ma_Plug, name='Ma_Plug'),
	path('wasee/', views.Plug_Products.wasee, name='wasee'),
	path('Mali', views.Plug_Products.as_view(), name='Mali'),
	path('posts', views.PostsView.as_view(), name='pos'),
	path('search', views.search, name='search'),
	path('profile/<str:pk>/<user>', views.Plug_Products.as_view(), name='plug_profile'),
	path('like-post', views.like_post, name='like_post'),
	path('MboaNFTs', MboaNFTs, name='MboaNFTs'),

]

sleek_main_hub/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	# For login to the Administrator Portal Only For SuperUsers
	path('admin/', admin.site.urls),
	
	
	# Can be accessed without Registration or login to the system. Basic lightweight function that require no Identity
	path('', include('sleek_profile.urls'), name="dashboard"),
	path('plug/', include('plug.urls'), name="plug"),
	path('', include('openSoko.urls', namespace="core"), name="core"),
	path('users/', include('plug.urls'), name="plug"),

	path("__reload__/", include("django_browser_reload.urls")),
	
	
	path('accounts/', include('accounts.urls'), name='accounts'),
	path('Notification/', include('conversation.urls'), name='banja'),
	path('mpesa/', include('mpesa.urls'), name='mpesa'),
	path('transactions/', include('transactions.urls'), name='transactions'),
	path('peer_to_peer/', include('peer_to_peer.urls'), name="peer_to_peer"),
	path('positions/', include('positions.urls'), name="positions"),
	
	
]
urlpatterns = urlpatterns+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = urlpatterns+static(settings.MBOA_ID_URL, document_root=settings.MBOA_ID_ROOT)

transactions/urls.py
from django.urls import path
from mpesa import views
from .views import DepositMoneyView, WithdrawMoneyView, LoanView, TransactionRepostView, eshopCart, MboaCoins, Invest


app_name = 'transactions'


urlpatterns = [
    path("stk", views.stk, name="stk"),
    path("deposit/", DepositMoneyView.as_view(), name="deposit_money"),
    path("report/", TransactionRepostView.as_view(), name="transaction_report"),
    path("withdraw/", WithdrawMoneyView.as_view(), name="withdraw_money"),
    path("mboapay/", eshopCart.as_view(), name="mboapay"),
    path("Invest", Invest, name="Invest"),
    path("mboaCoins/", MboaCoins.as_view(), name="eshopcart"),
    path("Loan", LoanView.as_view(), name="Loan"),
]

transactions/models.py
from django.db import models

from .constants import TRANSACTION_TYPE_CHOICES
from accounts.models import UserBankAccount


class Transaction(models.Model):
    account = models.ForeignKey(
        UserBankAccount,
        related_name='transactions',
        on_delete=models.CASCADE,
    )
    amount = models.DecimalField(
        decimal_places=2,
        max_digits=12
    )
    balance_after_transaction = models.DecimalField(
        decimal_places=2,
        max_digits=12
    )
    transaction_type = models.PositiveSmallIntegerField(
        choices=TRANSACTION_TYPE_CHOICES
    )
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.account.account_no)

    class Meta:
        ordering = ['timestamp']

transactions/forms.py
import datetime

from django import forms
from django.conf import settings

from .models import Transaction


class TransactionForm(forms.ModelForm):

    class Meta:
        model = Transaction
        fields = [
            'amount',
            'transaction_type'
        ]

    def __init__(self, *args, **kwargs):
        self.account = kwargs.pop('account')
        super().__init__(*args, **kwargs)

        self.fields['transaction_type'].disabled = True
        self.fields['transaction_type'].widget = forms.HiddenInput()

    def save(self, commit=True):
        self.instance.account = self.account
        self.instance.balance_after_transaction = self.account.balance
        return super().save()


class DepositForm(TransactionForm):

    def clean_amount(self):
        min_deposit_amount = float(settings.MINIMUM_DEPOSIT_AMOUNT)
        amount = self.cleaned_data.get('amount')

        if amount < min_deposit_amount:
            raise forms.ValidationError(
                f'You need to deposit at least    Ksh. {min_deposit_amount} '
            )

        return amount


class WithdrawForm(TransactionForm):

    def clean_amount(self):
        account = self.account
        min_withdraw_amount = float(settings.MINIMUM_WITHDRAWAL_AMOUNT)
        max_withdraw_amount = (
            account.account_type.maximum_withdrawal_amount
        )
        balance = account.balance

        amount = self.cleaned_data.get('amount')

        if amount < min_withdraw_amount:
            raise forms.ValidationError(
                f'You can only withdraw at least   Ksh.{min_withdraw_amount} '
            )

        if amount > max_withdraw_amount:
            raise forms.ValidationError(
                f'You can only withdraw at most   Ksh.{max_withdraw_amount} '
            )

        if amount > balance:
            raise forms.ValidationError(
                f'You have    Ksh.{balance}  in your account. '
                'You can not withdraw more than your account balance'
            )

        return amount


class TransactionDateRangeForm(forms.Form):
    daterange = forms.CharField(required=False)

    def clean_daterange(self):
        daterange = self.cleaned_data.get("daterange")
        print(daterange)

        try:
            daterange = daterange.split(' - ')
            print(daterange)
            if len(daterange) == 2:
                for date in daterange:
                    datetime.datetime.strptime(date, '%Y-%m-%d')
                return daterange
            else:
                raise forms.ValidationError("Please select a date range.")
        except (ValueError, AttributeError):
            raise forms.ValidationError("Invalid date range")


class eshopCart_Form(forms.ModelForm):

    class Meta:
        model = Transaction
        fields = [
            'amount',
            'transaction_type'
        ]

    def __init__(self, *args, **kwargs):
        self.account = kwargs.pop('account')
        super().__init__(*args, **kwargs)

        self.fields['transaction_type'].disabled = True
        self.fields['transaction_type'].widget = forms.HiddenInput()

    def save(self, commit=True):
        self.instance.account = self.account
        self.instance.balance_after_transaction = self.account.balance
        return super().save()


class MboaCoins_Form(forms.ModelForm):

    class Meta:
        model = Transaction
        fields = [
            'amount',
            'transaction_type'
        ]

    def __init__(self, *args, **kwargs):
        self.account = kwargs.pop('account')
        super().__init__(*args, **kwargs)

        self.fields['transaction_type'].disabled = True
        self.fields['transaction_type'].widget = forms.HiddenInput()

    def save(self, commit=True):
        self.instance.account = self.account
        self.instance.balance_after_transaction = self.account.balance
        return super().save()


class LoanForm(TransactionForm):

    def clean_amount(self):
        min_Loan_amount = float(settings.MINIMUM_LOAN_AMOUNT)
        max_Loan_amount = float(settings.MAXIMUM_LOAN_AMOUNT)
        amount = self.cleaned_data.get('amount')

        if amount < min_Loan_amount:
            raise forms.ValidationError(
                f'You need to Borrow at least    Ksh. {min_Loan_amount} '
            )

        if amount > max_Loan_amount:
            raise forms.ValidationError(
                f'You Borrow limit is   Ksh. {max_Loan_amount} '
                f'Try a lower amount Please'
            )

        return amount

transactions/views.py
from dateutil.relativedelta import relativedelta

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import CreateView, ListView

from transactions.constants import DEPOSIT, WITHDRAWAL, MBOAPAY, LOAN, MBOACOINS
from transactions.forms import (
    DepositForm,
    TransactionDateRangeForm,
    WithdrawForm,
    eshopCart_Form,
    LoanForm,
    MboaCoins_Form,
)
from transactions.models import Transaction


class TransactionRepostView(LoginRequiredMixin, ListView):
    template_name = 'transactions/transaction_report.html'
    model = Transaction
    form_data = {}

    def get(self, request, *args, **kwargs):
        form = TransactionDateRangeForm(request.GET or None)
        if form.is_valid():
            self.form_data = form.cleaned_data

        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        queryset = super().get_queryset().filter(
            account=self.request.user.account
        )

        daterange = self.form_data.get("daterange")

        if daterange:
            queryset = queryset.filter(timestamp__date__range=daterange)

        return queryset.distinct()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'account': self.request.user.account,
            'form': TransactionDateRangeForm(self.request.GET or None)
        })

        return context


class TransactionCreateMixin(LoginRequiredMixin, CreateView):
    template_name = 'transactions/transaction_form.html'
    model = Transaction
    title = ''
    success_url = reverse_lazy('transactions:transaction_report')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({
            'account': self.request.user.account
        })
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'title': self.title
        })

        return context


class DepositMoneyView(TransactionCreateMixin):
    form_class = DepositForm
    title = 'Deposit.Top-up your account🤑'

    def get_initial(self):
        initial = {'transaction_type': DEPOSIT}
        return initial

    def form_valid(self, form):
        amount = form.cleaned_data.get('amount')
        account = self.request.user.account
        #pesa = views.stk(amount)

        if not account.initial_deposit_date:
            now = timezone.now()
            next_interest_month = int(
                12 / account.account_type.interest_calculation_per_year
            )
            account.initial_deposit_date = now
            account.interest_start_date = (
                now + relativedelta(
                    months=+next_interest_month
                )
            )

        account.balance += amount
        account.save(
            update_fields=[
                'initial_deposit_date',
                'balance',
                'interest_start_date'
            ]
        )

        messages.success(
            self.request,
            f' Wazi Bro!  Ksh.{amount} was deposited to your account successfully'
        )

        return super().form_valid(form)


class WithdrawMoneyView(TransactionCreateMixin):
    form_class = WithdrawForm
    title = 'Withdraw funds'

    def get_initial(self):
        initial = {'transaction_type': WITHDRAWAL}
        return initial

    def form_valid(self, form):
        amount = form.cleaned_data.get('amount')

        self.request.user.account.balance -= form.cleaned_data.get('amount')
        self.request.user.account.save(update_fields=['balance'])

        messages.success(
            self.request,
            f' Wazi Bro!  Successfully withdrawn  Ksh.{amount} from your account'
        )

        return super().form_valid(form)


class eshopCart(TransactionCreateMixin):
    template_name = 'transactions/Mboapay/Mboapay.html'
    form_class = eshopCart_Form
    title = 'Mboapay - Online Purchase of MboaCoins'

    def get_initial(self):
        initial = {'transaction_type': MBOAPAY}
        return initial

    def form_valid(self, form):
        amount = form.cleaned_data.get('amount')

        self.request.user.account.balance -= form.cleaned_data.get('amount')
        self.request.user.account.save(update_fields=['balance'])

        messages.success(
            self.request,
            f'Wazi Bro! Successfully Used Mboapay. Hi , Ksh.{amount}  Withdrawn from your account for Payments'
        )

        return super().form_valid(form)
    
    
class MboaCoins(TransactionCreateMixin):
    form_class = MboaCoins_Form
    title = 'Buy Mboa Coins Now'

    def get_initial(self):
        initial = {'transaction_type': MBOACOINS}
        return initial

    def form_valid(self, form):
       
        amount = form.cleaned_data.get('amount')
        account = self.request.user.account
        amountx = amount/500

        if not account.initial_deposit_date:
            now = timezone.now()
            next_interest_month = int(
                12 / account.account_type.interest_calculation_per_year
            )
            account.initial_deposit_date = now
            account.interest_start_date = (
                now + relativedelta(
                    months=+next_interest_month
                )
            )

        account.balance -= amount
        account.save(
            update_fields=[
                'initial_deposit_date',
                'balance',
                'interest_start_date'
            ]
        )

        messages.success(
            self.request,
            f'  Nice Move,  {amountx} MboaCoins   Deposited to your Mboa-ID account successfully'
        )

        return super().form_valid(form)


class LoanView(TransactionCreateMixin):
    form_class = LoanForm
    title = 'Enter loan Amount You Need'
    
    def get_initial(self):
        initial = {'transaction_type': LOAN}
        return initial
    
    def form_valid(self, form):
        amount = form.cleaned_data.get('amount')
        account = self.request.user.account
       
        Fee = int(amount) * 1/20
        
        if not account.initial_deposit_date:
            now = timezone.now()
            next_interest_month = int(
                12 / account.account_type.interest_calculation_per_year
            )
            account.initial_deposit_date = now
            account.interest_start_date = (
                    now + relativedelta(months=+next_interest_month)
            )
        
        account.balance += amount
        account.save(
            update_fields=[
                'initial_deposit_date',
                'balance',
                'interest_start_date'
            ]
        )
        
        messages.success(
            self.request,
            f'  Congratulations! Loan Approved '
            f'Ksh.{amount} Deposited to your Mboa-ID account successfully'
            f'You will repay with a fee of {Fee}.'
            f'Kindly Payback Before : {account.interest_start_date} and avoid Penalties..'
        )
        
        return super().form_valid(form)


def Invest(request):
    # model = Item
    return render(request, 'mpesa/invest.html')

templates/transactions/transaction_form.html
{% extends 'core/base.html' %}

{% block head_title %}{{ title }}{% endblock %}

{% block content %}
{%load static%}
<section class="home-section align-items-center" style="background-color:rgba(0,0,0,0.2);
        opacity:90%; border-radius:40px;backdrop-filter:blur(10px);border:2px solid rgba(255,255,255,0.2);z-index:10;display:flex;box-shadow:40px 40px 40px 80px rgba(0,0,0,0.3);" id ="support">
    <div class="container">
               <div class="row align-items-center">
                  <div class="home-text">
                                <div style="border: 3px solid #001100;opacity:100%;width:100%;color:white;margin: 2px; padding:5%; border-radius:24px;margin-right:20px;font-size:80%;">
                                            <img class="img-fluid" style="width:100px; height:100px ; border-radius:100%; opacity:100%; margin-top:5vh;" src=" {{user.address.profileimg.url}}"  alt="Profile Picture for {{ user.first_name }}">
                           <h1 style="color:#001100;"> {{ title }}</h1>
                                        <hr style="width:100%;height:1px;"/>
                               <h4  >
                               </h4>
 <form method="post" class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
        {% csrf_token %}

        <div class="mb-4">
           <!-- <label class="bty block text-gray-700 text-sm font-bold mb-2" for="amount">
                Amount (KES)
            </label>
            -->
            <center>
            <input  style="text-align:center;width:100%;margin-top:20px;color:#001100;border:2px solid #6BBE4E;" autofocus class="btn shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight border rounded-md border-gray-500 focus:outline-none focus:shadow-outline" name="amount" id="amount" type="number" required placeholder="Amount in Ksh">
            </center>
        </div>

        {% if form.amount.errors %}
            {% for error in form.amount.errors %}
                <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
            {% endfor %}
        {% endif %}

            <button  style="text-align:center; margin-top:10vh; color:#f6f4f0; background-color:#000; border-radius:7px; width:100%;height:50px;padding:3%;" class="bty " type="submit"> <a style="color:#ffffff;">Confirm</a> </button>

    </form>

</div>
                  </div>
<div class="home-text">
<div  style="margin-top:5vh;" class="w-full mt-5">
                 <center>



     <button style=" margin-top:20px; background-color:#6BBE4E;color:#f6f4f0;" class="bty bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" >
            <a style="color:#F7F9F0;"  href="/transactions/report">Transaction History</a>
        </button>


    <button style=" margin-top:20px;  background-color:#ffffff00;color:#f6f4f0;" class="bty bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" ><a  style="color:#F7F9F0;" href="/mpesa/Offline">Offline Transaction</a>
        </button>
                       </center>
</div>
               </div>
    </div>
    </div> </section>




{% endblock %}

templates/transactions/transaction_report.html
{% extends 'core/No_base.html' %}
{%load static%}
{% block head_title %}Transaction History{% endblock %}

{% block head_extra %}
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Tangerine">
   <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">
    <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
{% endblock %}

{% block content %}

 <section  style=";width:100%; background-color:rgba(0,0,0,0.2);border-radius:40px;backdrop-filter:blur(10px);border:2px solid rgba(255,255,255,0.2);z-index:10;display:flex;box-shadow:40px 40px 40px 80px rgba(0,0,0,0.3);" class="home-section align-items-center" id ="home">
   <div class="container">
          {% for message in messages %}
                       <div  class="bty bg-teal-100 border-t-4 border-teal-500 rounded-b text-teal-900 px-4 py-3 shadow-md mt-2"
      style="z-index:10px;backdrop-filter:blur(10px);margin:5%;border-radius:10px;border:2px solid rgba(255,255,255,0.2); width:80%; background-color:none"  role="alert">
                  <div style="display:flex;flex-direction:row;height:100%;">
                   <img style="opacity:10%;  margin-left:-10%;width:100px; height:100px;" class="logoKenya"   src="{% static 'img/KenyanBrand.jpg'%}" alt="profile-img">
                      <div style="margin-left: -10%;width:90%;height:10vh;" class="flex">
            <p style="color:green" class="font-bold">Confirmed:-</p>
            <p style="font-weight:bold;margin-top:10px;color:#001100" class="text-sm block sm:inline">{{ message }}</p>
        </div>
                      </div>

     <button  style="margin-right:-10vw;width:100%;border:none;background-color:#ffffff00;margin-top:1vh;" type="button" class="bty ">
                    <a style="color:red;" href="/transactions/report"><i class="fas fa-times"> </i> </a> </button>

</div>
          {% endfor %}
        <div class="row align-items-center">
                      <h1 class="font-mono font-bold text-3xl text-center pb-5 pt-10" style="margin:5%;">Transaction History</h1> <br>
   <hr style="width:100%;height:1px;">
    <form method="get">
        <div class="mt-10 h-10 pl-3 pr-2 bg-white border rounded-md border-gray-500 flex justify-between items-center relative" style="margin-left:4%;">
            <input type="search" name="daterange" id="search" style="margin-left:2%;" placeholder="Filter using date range" value="{{ request.GET.daterange }}" class=" bty appearance-none w-full outline-none focus:outline-none active:outline-none" />
            <button type="submit" class="ml-1 outline-none focus:outline-none active:outline-none"   >
               </button>

        <script type="text/javascript">
        $(function () {
            $('input[name="daterange"]').daterangepicker({
                autoUpdateInput: false,
                locale: {
                    cancelLabel: "Clear",
                },
            });

            $('input[name="daterange"]').on("apply.daterangepicker", function (ev, picker) {
                $(this).val(picker.startDate.format("YYYY-MM-DD") + " - " + picker.endDate.format("YYYY-MM-DD"));
            });

            $('input[name="daterange"]').on("cancel.daterangepicker", function (ev, picker) {
                $(this).val("");
            });
        });
    </script>
             </div>
        {% if form.daterange.errors %}
            {% for error in form.daterange.errors %}
                <p style="margin:5%;" class="text-red-600 text-sm italic">{{ error }}</p>
            {% endfor %}
        {% endif %}
    </form>
    <table style="font-size:80%;padding:2%; border-radius:2px;font-family:Comic Sans Mn;font-weight:bold;" class="bty home-txt table-auto mx-auto w-full mt-8">
        <thead class="bg-gray-800 text-white">
        <tr class="uppercase font-semibold text-sm">
            <th class="px-4 py-2">Date</th>
            <th class="px-4 py-2">TransactionType</th>
            <th class="px-4 py-2">Amount in Ksh. </th>
            <th class="px-4 py-2">Balance in Ksh. </th>
        </tr>
        </thead>
        <tbody>
        {% for transaction in object_list %}
        <tr class="{% cycle 'bg-gray-300' 'bg-white-100' %}">
             <td class="border px-4 py-2 text-center">{{ transaction.timestamp }}</td>
            <td class="border px-4 py-2 text-center" style="margin:10%;">{{ transaction.get_transaction_type_display }}</td>
            <td class="border px-4 py-2 text-center">{{ transaction.amount }}</td>
            <td class="border px-4 py-2 text-center">{{ transaction.balance_after_transaction }}</td>
        </tr>
        {% endfor %}
        <tr  class="bg-gray-600 text-white">
            <th class="px-4 py-2 text-right" colspan="3">Final Balance</th>
            <th class="px-4 py-2 text-center">Ksh.{{ account.balance }}</th>
        </tr>
        </tbody>
    </table>
                  </div>
        {% block footer_extra %}

        {% endblock %}
               </div>

</section>




{% endblock %}